module.exports = {
    'REFRESH_ACTIVE_TAB': 'REFRESH_ACTIVE_TAB',
    'REFRESH_ALL': 'REFRESH_ALL',
    'COMPONENT_OUTPUT_ACTIVE_OBJECT_CHANGE': 'COMPONENT_OUTPUT_ACTIVE_OBJECT_CHANGE',
    'COMPONENT_OUTPUT_CHANGE': 'COMPONENT_OUTPUT_CHANGE',
    'CLEAR_USE_FROM_ABOVE_FILTERS': 'CLEAR_USE_FROM_ABOVE_FILTERS',
    'CLEAR_ACTIVE_TAB_USE_FROM_ABOVE_FILTERS': 'CLEAR_ACTIVE_TAB_USE_FROM_ABOVE_FILTERS',

    'ATTRIBUTE_DATA_SERVICE_INITIALIZED': 'ATTRIBUTE_DATA_SERVICE_INITIALIZED',
    'VIEWER_TABLE_COLUMNS_CHANGED': 'VIEWER_TABLE_COLUMNS_CHANGED',
    'SAVE_VIEWER_TABLE_CONFIGURATION': 'SAVE_VIEWER_TABLE_CONFIGURATION',

    // dashboard component events
    'COMPONENT_STATUS_CHANGE': 'COMPONENT_STATUS_CHANGE',
    'RELOAD_COMPONENT': 'RELOAD_COMPONENT',
    'RELOAD_CONTENT_OF_COMPONENT': 'RELOAD_CONTENT_OF_COMPONENT',

    'UPDATE_VIEWER_TABLE_COLUMNS': 'UPDATE_VIEWER_TABLE_COLUMNS',

    'OPEN_COMPONENT_EDITOR': 'OPEN_COMPONENT_EDITOR',

    'COMPONENT_BLOCKAGE_ON': 'COMPONENT_BLOCKAGE_ON',
    'COMPONENT_BLOCKAGE_OFF': 'COMPONENT_BLOCKAGE_OFF'

};