module.exports = {
    'REFRESH_ACTIVE_TAB': 'REFRESH_ACTIVE_TAB',
    'REFRESH_ALL': 'REFRESH_ALL',
    'COMPONENT_STATUS_CHANGE': 'COMPONENT_STATUS_CHANGE',

    'ATTRIBUTE_DATA_SERVICE_INITIALIZED': 'ATTRIBUTE_DATA_SERVICE_INITIALIZED',
    'VIEWER_TABLE_COLUMNS_CHANGED': 'VIEWER_TABLE_COLUMNS_CHANGED',
    'UPDATE_VIEWER_TABLE_COLUMNS': 'UPDATE_VIEWER_TABLE_COLUMNS',
    'SAVE_VIEWER_TABLE_CONFIGURATION': 'SAVE_VIEWER_TABLE_CONFIGURATION',

    // dashboard component events
    'RELOAD_COMPONENT': 'RELOAD_COMPONENT',
    'RELOAD_CONTENT_OF_COMPONENT': 'RELOAD_CONTENT_OF_COMPONENT'
};