module.exports = {
    'COLUMNS_CHANGE': 'COLUMNS_CHANGE',
    'FILTERS_CHANGE': 'FILTERS_CHANGE',
    'GROUPS_CHANGE': 'GROUPS_CHANGE',

    'UPDATE_TABLE': 'UPDATE_TABLE', // async download
    'REDRAW_TABLE': 'REDRAW_TABLE', // inmemory redraw

    'PAGE_CHANGE': 'PAGE_CHANGE',
    'ADDITIONS_CHANGE': 'ADDITIONS_CHANGE',
    'ADDITIONS_EDITOR_ENTITY_ID_CHANGE': 'ADDITIONS_EDITOR_ENTITY_ID_CHANGE',


    'ADDITIONS_RENDER': 'ADDITIONS_RENDER',

    'RESIZE_COLUMNS': 'RESIZE_COLUMNS',
    'UPDATE_COLUMNS_SIZE': 'UPDATE_COLUMNS_SIZE',
    'UPDATE_TABLE_HEAD_COLUMNS_SIZE': 'UPDATE_TABLE_HEAD_COLUMNS_SIZE',

    'CALCULATE_REPORT': 'CALCULATE_REPORT',
    'DATA_LOAD_END': 'DATA_LOAD_END',
    'DATA_LOAD_START': 'DATA_LOAD_START',


    'ACTIVE_OBJECT_CHANGE': 'ACTIVE_OBJECT_CHANGE', // right click on object info


    'COLUMN_SORT_CHANGE': 'COLUMN_SORT_CHANGE',
    'GROUP_TYPE_SORT_CHANGE': 'GROUP_TYPE_SORT_CHANGE'
};