module.exports = {
    'COLUMNS_CHANGE': 'COLUMNS_CHANGE',
    'FILTERS_CHANGE': 'FILTERS_CHANGE',
    'GROUPS_CHANGE': 'GROUPS_CHANGE',

    'UPDATE_TABLE': 'UPDATE_TABLE', // async download
    'REDRAW_TABLE': 'REDRAW_TABLE', // inmemory redraw
    'UPDATE_PROJECTION': 'UPDATE_PROJECTION',

    'PAGE_CHANGE': 'PAGE_CHANGE',
    'ADDITIONS_CHANGE': 'ADDITIONS_CHANGE',

    'RESIZE_COLUMNS_START': 'RESIZE_COLUMNS_START',
    'RESIZE_COLUMNS_END': 'RESIZE_COLUMNS_END',
    'UPDATE_COLUMNS_SIZE': 'UPDATE_COLUMNS_SIZE',
    'UPDATE_TABLE_HEAD_COLUMNS_SIZE': 'UPDATE_TABLE_HEAD_COLUMNS_SIZE',
    'START_CELLS_OVERFLOW': 'START_CELLS_OVERFLOW',

    'REQUEST_REPORT': 'REQUEST_REPORT',
    'DATA_LOAD_END': 'DATA_LOAD_END',
    'DATA_LOAD_START': 'DATA_LOAD_START',


    'ACTIVE_OBJECT_CHANGE': 'ACTIVE_OBJECT_CHANGE', // right click on object info

    'ACTIVE_OBJECT_FROM_ABOVE_CHANGE': 'ACTIVE_OBJECT_FROM_ABOVE_CHANGE', // for active object for split panel from root entity viewer


    'COLUMN_SORT_CHANGE': 'COLUMN_SORT_CHANGE',
    'GROUP_TYPE_SORT_CHANGE': 'GROUP_TYPE_SORT_CHANGE',


    'GROUPS_LEVEL_FOLD': 'GROUPS_LEVEL_FOLD',
    'GROUPS_LEVEL_UNFOLD': 'GROUPS_LEVEL_UNFOLD',


    'UPDATE_EV_UI': 'UPDATE_EV_UI',
    'TOGGLE_FILTER_AREA': 'TOGGLE_FILTER_AREA',
    'UPDATE_FILTER_AREA_SIZE': 'UPDATE_FILTER_AREA_SIZE',

    'UPDATE_TABLE_VIEWPORT': 'UPDATE_TABLE_VIEWPORT', // recalculate height and width for ev-viewport
    'UPDATE_ENTITY_VIEWER_CONTENT_WRAP_SIZE': 'UPDATE_ENTITY_VIEWER_CONTENT_WRAP_SIZE',


    'REPORT_OPTIONS_CHANGE': 'REPORT_OPTIONS_CHANGE',

    'LIST_LAYOUT_CHANGE': 'LIST_LAYOUT_CHANGE',

    // Events used only to track layout changes
    'REPORT_EXPORT_OPTIONS_CHANGED': 'REPORT_EXPORT_OPTIONS_CHANGED',
    'REPORT_TABLE_VIEW_CHANGED': 'REPORT_TABLE_VIEW_CHANGED',

    // Trigger Split Panel events from root entity viewer

    'UPDATE_SPLIT_PANEL_TABLE_VIEWPORT': 'UPDATE_SPLIT_PANEL_TABLE_VIEWPORT',
    'SPLIT_PANEL_DEFAULT_LIST_LAYOUT_CHANGED': 'SPLIT_PANEL_DEFAULT_LIST_LAYOUT_CHANGED'
};