module.exports = {
    'CELL_VALUE_CHANGED': 'CELL_VALUE_CHANGED',
    'SELECTOR_INSIDE_CELL_OPENED': 'SELECTOR_INSIDE_CELL_OPENED',
    'ROWS_DELETED': 'ROWS_DELETED',

    'ROW_SELECTION_TOGGLED': 'ROW_SELECTION_TOGGLED',
    'SORTING_SETTINGS_CHANGED': 'SORTING_SETTINGS_CHANGED'
};